remove tag step from dev

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,10 +5,6 @@ on:
         description: Environment to which code will be deployed
         required: true
         type: string
-      version:
-        description: Current app version
-        required: true
-        type: string
       filename:
         description: .zip filename (not including extension)
         required: true
@@ -27,68 +23,9 @@ permissions:
   contents: write # This is required for actions/checkout and tag creation
 
 jobs:
-  UpdateGitTag:
-    runs-on: ubuntu-latest
-    # Do not need to worry about tag for Dev deployments.
-    if: ${{ inputs.env != 'dev' }}
-    outputs:
-      version_tag_exists: ${{ steps.check_tag.outputs.tag_exists }}
-    steps:
-      - name: Define tag
-        id: define_tag
-        run: |
-          TAG=${{ inputs.version }}
-          echo "tag=$TAG" >> $GITHUB_OUTPUT
-          echo "tag=$TAG"
-
-      - name: Git clone the repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Need this to get all tags.
-
-      - name: Check if tag exists
-        id: check_tag
-        run: |
-          echo $(git rev-parse --quiet --verify "refs/tags/${{ inputs.version }}")
-          if git rev-parse --quiet --verify "refs/tags/${{ inputs.version }}"; then
-            echo "Tag '${{ inputs.version }}' exists."
-            TAG_EXISTS=true
-          else
-            echo "Tag '${{ inputs.version }}' does not exist."
-            TAG_EXISTS=false
-          fi
-          echo "tag_exists=$TAG_EXISTS" >> $GITHUB_OUTPUT
-          echo "tag_exists: $TAG_EXISTS"
-
-      - name: Create Git tag
-        if: steps.check_tag.outputs.tag_exists != 'true'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            github.rest.git.createRef({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              ref: '${{ steps.define_tag.outputs.tag }}',
-              sha: context.sha
-            })
-
   BuildAndUploadToS3:
-    needs: [UpdateGitTag]
     runs-on: ubuntu-latest
-    # We can make dev deployments without a new tag.
-    if: ${{ ! needs.UpdateGitTag.outputs.version_tag_exists }} || ${{ inputs.env == 'dev' }}
     steps:
-      - name: Exit if current version is uploaded
-        run: |
-          echo "! needs.UpdateGitTag.outputs.version_tag_exists = ${{ ! needs.UpdateGitTag.outputs.version_tag_exists  }}""
-          echo "Tag for current version already exists: ${{ needs.UpdateGitTag.outputs.version_tag_exists }}"
-          if ${{ needs.UpdateGitTag.outputs.version_tag_exists }} = "true"; then
-            echo "Version is already tagged and uploaded to S3. Exiting."
-          else 
-            echo "Version is not yet uploaded to S3. Proceeding with build and upload"
-          fi
-          exit 0
-
       - name: Git clone the repository
         uses: actions/checkout@v4
 
@@ -108,6 +45,20 @@ jobs:
           cd src
           zip -r ../$FILENAME *.py commands data_helpers
         # Put file in starting working directory.
+
+      - name: Check if file exists
+        # This is to avoid overwriting releases. Overwriting dev deployments is safe.
+        if: ${{ inputs.env != 'dev' }}
+        run: |
+          if aws s3 ls s3://${{ secrets.BUCKET_NAME }}/${{ steps.zip_files.outputs.filename }};
+          then
+            echo "File ${{ steps.zip_files.outputs.filename }} already exists."
+            echo "Build failure: cannot overwrite existing release outside of dev."
+            exit 1
+          else
+            echo "File ${{ steps.zip_files.outputs.filename }} not found in S3. Proceeding with upload to S3."
+          fi
+        # Call exit 1 to fail this job.
 
       - name: Deploy to S3
         run: aws s3 cp ${{ steps.zip_files.outputs.filename }} s3://${{ secrets.BUCKET_NAME }}
